### ISSUE TITLE
Read a .gutma file

### ISSUE THREAD

**Issue by emmaemmstein** [gutma-org/flight-logging-protocol#3]
I have a number of files saved in .gutma format, how do I read a .gutma file?

Thanks

**Comment by hrishiballal** [comment]
Hi @emmaemmstein , you will have to write a parser to read them, I dont think that's open-source

**Comment by emmaemmstein** [comment]
Thank you @hrishiballal. Looking at the file it seem similar to a json file. Can you point me to what I need to know and do to create a parser (using Python)? I'd say I have an appreciable knowledge of python programming but not to an expert level. Thanks

**Comment by emmaemmstein** [comment]
gutma files can be parsed as would a json file. Thanks
